[package]
name = "geosetta"
version = "0.18.0"
edition = "2024"
description = "Convert between open vector geospatial formats (GeoJSON, GeoParquet, FlatGeobuf, GeoPackage, CSV, WKT), dependency-free."
license = "MIT"

[lib]
name = "geosetta"
path = "src/lib.rs"

[[bin]]
name = "geosetta"
path = "src/main.rs"

[dependencies]

[profile.release]
lto = true
codegen-units = 1
