//! GENERATED by tests/fixtures/gen_wkt1_crosswalk.py — do not edit by hand.
//! Source: PROJ EPSG registry via projinfo (622 CRSes, cap 200/method).
//!
//! WKT1 (GDAL flavor) carries GDAL's projection/parameter names with no EPSG
//! ids; these tables restore the ids PROJJSON needs. Keyed data only — the
//! translation logic lives in `wkt_projjson.rs`.

use super::wkt_projjson::UnitKind;

/// WKT1 GDAL `PROJECTION` name -> (canonical PROJJSON method name, EPSG code,
/// en_default_safe). When `en_default_safe` is false the method has CRSes whose
/// true CS is not easting/northing yet whose WKT1 omits `AXIS`; the translator
/// then resolves only AXIS-bearing CRSes and falls back on the rest.
pub(super) static METHODS: &[(&str, &str, i64, bool)] = &[
    ("Albers_Conic_Equal_Area", "Albers Equal Area", 9822, false),
    ("Bonne_(South_Orientated)", "Bonne (South Orientated)", 9828, false),
    ("Cassini_Soldner", "Cassini-Soldner", 9806, false),
    ("Equirectangular", "Equidistant Cylindrical", 1028, true),
    ("Hotine_Oblique_Mercator", "Hotine Oblique Mercator (variant A)", 9812, true),
    ("Hotine_Oblique_Mercator_Azimuth_Center", "Hotine Oblique Mercator (variant B)", 9815, false),
    ("Laborde_Oblique_Mercator", "Laborde Oblique Mercator", 9813, false),
    ("Lambert_Conformal_Conic_1SP", "Lambert Conic Conformal (1SP)", 9801, false),
    ("Lambert_Conformal_Conic_2SP", "Lambert Conic Conformal (2SP)", 9802, false),
    ("Lambert_Conformal_Conic_2SP_Belgium", "Lambert Conic Conformal (2SP Belgium)", 9803, true),
    ("Lambert_Conic_Conformal_(West_Orientated)", "Lambert Conic Conformal (West Orientated)", 9826, false),
    ("Lambert_Conic_Near-Conformal", "Lambert Conic Near-Conformal", 9817, true),
    ("Local Orthographic", "Local Orthographic", 1130, true),
    ("Mercator_2SP", "Mercator (variant B)", 9805, false),
    ("New_Zealand_Map_Grid", "New Zealand Map Grid", 9811, true),
    ("Oblique_Stereographic", "Oblique Stereographic", 9809, false),
    ("Polar_Stereographic_(variant_C)", "Polar Stereographic (variant C)", 9830, false),
    ("Polyconic", "American Polyconic", 9818, true),
    ("Transverse_Mercator", "Transverse Mercator", 9807, false),
    ("Transverse_Mercator_South_Orientated", "Transverse Mercator (South Orientated)", 9808, false),
    ("Transverse_Mercator_Zoned_Grid_System", "Transverse Mercator Zoned Grid System", 9824, true),
    ("Tunisia_Mining_Grid", "Tunisia Mining Grid", 9816, true),
];

/// (EPSG method code, WKT1 GDAL parameter name)
///     -> (canonical PROJJSON parameter name, EPSG code, unit kind).
pub(super) static PARAMS: &[(i64, &str, &str, i64, UnitKind)] = &[
    (1028, "central_meridian", "Longitude of natural origin", 8802, UnitKind::Angular),
    (1028, "false_easting", "False easting", 8806, UnitKind::Linear),
    (1028, "false_northing", "False northing", 8807, UnitKind::Linear),
    (1028, "standard_parallel_1", "Latitude of 1st standard parallel", 8823, UnitKind::Angular),
    (1130, "azimuth", "Azimuth at projection centre", 8813, UnitKind::Angular),
    (1130, "false_easting", "Easting at projection centre", 8816, UnitKind::Linear),
    (1130, "false_northing", "Northing at projection centre", 8817, UnitKind::Linear),
    (1130, "latitude_of_center", "Latitude of projection centre", 8811, UnitKind::Angular),
    (1130, "longitude_of_center", "Longitude of projection centre", 8812, UnitKind::Angular),
    (1130, "scale_factor", "Scale factor at projection centre", 8815, UnitKind::Scale),
    (9801, "central_meridian", "Longitude of natural origin", 8802, UnitKind::Angular),
    (9801, "false_easting", "False easting", 8806, UnitKind::Linear),
    (9801, "false_northing", "False northing", 8807, UnitKind::Linear),
    (9801, "latitude_of_origin", "Latitude of natural origin", 8801, UnitKind::Angular),
    (9801, "scale_factor", "Scale factor at natural origin", 8805, UnitKind::Scale),
    (9802, "central_meridian", "Longitude of false origin", 8822, UnitKind::Angular),
    (9802, "false_easting", "Easting at false origin", 8826, UnitKind::Linear),
    (9802, "false_northing", "Northing at false origin", 8827, UnitKind::Linear),
    (9802, "latitude_of_origin", "Latitude of false origin", 8821, UnitKind::Angular),
    (9802, "standard_parallel_1", "Latitude of 1st standard parallel", 8823, UnitKind::Angular),
    (9802, "standard_parallel_2", "Latitude of 2nd standard parallel", 8824, UnitKind::Angular),
    (9803, "central_meridian", "Longitude of false origin", 8822, UnitKind::Angular),
    (9803, "false_easting", "Easting at false origin", 8826, UnitKind::Linear),
    (9803, "false_northing", "Northing at false origin", 8827, UnitKind::Linear),
    (9803, "latitude_of_origin", "Latitude of false origin", 8821, UnitKind::Angular),
    (9803, "standard_parallel_1", "Latitude of 1st standard parallel", 8823, UnitKind::Angular),
    (9803, "standard_parallel_2", "Latitude of 2nd standard parallel", 8824, UnitKind::Angular),
    (9805, "central_meridian", "Longitude of natural origin", 8802, UnitKind::Angular),
    (9805, "false_easting", "False easting", 8806, UnitKind::Linear),
    (9805, "false_northing", "False northing", 8807, UnitKind::Linear),
    (9805, "standard_parallel_1", "Latitude of 1st standard parallel", 8823, UnitKind::Angular),
    (9806, "central_meridian", "Longitude of natural origin", 8802, UnitKind::Angular),
    (9806, "false_easting", "False easting", 8806, UnitKind::Linear),
    (9806, "false_northing", "False northing", 8807, UnitKind::Linear),
    (9806, "latitude_of_origin", "Latitude of natural origin", 8801, UnitKind::Angular),
    (9807, "central_meridian", "Longitude of natural origin", 8802, UnitKind::Angular),
    (9807, "false_easting", "False easting", 8806, UnitKind::Linear),
    (9807, "false_northing", "False northing", 8807, UnitKind::Linear),
    (9807, "latitude_of_origin", "Latitude of natural origin", 8801, UnitKind::Angular),
    (9807, "scale_factor", "Scale factor at natural origin", 8805, UnitKind::Scale),
    (9808, "central_meridian", "Longitude of natural origin", 8802, UnitKind::Angular),
    (9808, "false_easting", "False easting", 8806, UnitKind::Linear),
    (9808, "false_northing", "False northing", 8807, UnitKind::Linear),
    (9808, "latitude_of_origin", "Latitude of natural origin", 8801, UnitKind::Angular),
    (9808, "scale_factor", "Scale factor at natural origin", 8805, UnitKind::Scale),
    (9809, "central_meridian", "Longitude of natural origin", 8802, UnitKind::Angular),
    (9809, "false_easting", "False easting", 8806, UnitKind::Linear),
    (9809, "false_northing", "False northing", 8807, UnitKind::Linear),
    (9809, "latitude_of_origin", "Latitude of natural origin", 8801, UnitKind::Angular),
    (9809, "scale_factor", "Scale factor at natural origin", 8805, UnitKind::Scale),
    (9811, "central_meridian", "Longitude of natural origin", 8802, UnitKind::Angular),
    (9811, "false_easting", "False easting", 8806, UnitKind::Linear),
    (9811, "false_northing", "False northing", 8807, UnitKind::Linear),
    (9811, "latitude_of_origin", "Latitude of natural origin", 8801, UnitKind::Angular),
    (9812, "azimuth", "Azimuth at projection centre", 8813, UnitKind::Angular),
    (9812, "false_easting", "False easting", 8806, UnitKind::Linear),
    (9812, "false_northing", "False northing", 8807, UnitKind::Linear),
    (9812, "latitude_of_center", "Latitude of projection centre", 8811, UnitKind::Angular),
    (9812, "longitude_of_center", "Longitude of projection centre", 8812, UnitKind::Angular),
    (9812, "rectified_grid_angle", "Angle from Rectified to Skew Grid", 8814, UnitKind::Angular),
    (9812, "scale_factor", "Scale factor at projection centre", 8815, UnitKind::Scale),
    (9813, "azimuth", "Azimuth at projection centre", 8813, UnitKind::Angular),
    (9813, "false_easting", "False easting", 8806, UnitKind::Linear),
    (9813, "false_northing", "False northing", 8807, UnitKind::Linear),
    (9813, "latitude_of_center", "Latitude of projection centre", 8811, UnitKind::Angular),
    (9813, "longitude_of_center", "Longitude of projection centre", 8812, UnitKind::Angular),
    (9813, "scale_factor", "Scale factor at projection centre", 8815, UnitKind::Scale),
    (9815, "azimuth", "Azimuth at projection centre", 8813, UnitKind::Angular),
    (9815, "false_easting", "Easting at projection centre", 8816, UnitKind::Linear),
    (9815, "false_northing", "Northing at projection centre", 8817, UnitKind::Linear),
    (9815, "latitude_of_center", "Latitude of projection centre", 8811, UnitKind::Angular),
    (9815, "longitude_of_center", "Longitude of projection centre", 8812, UnitKind::Angular),
    (9815, "rectified_grid_angle", "Angle from Rectified to Skew Grid", 8814, UnitKind::Angular),
    (9815, "scale_factor", "Scale factor at projection centre", 8815, UnitKind::Scale),
    (9816, "central_meridian", "Longitude of false origin", 8822, UnitKind::Angular),
    (9816, "false_easting", "Easting at false origin", 8826, UnitKind::Linear),
    (9816, "false_northing", "Northing at false origin", 8827, UnitKind::Linear),
    (9816, "latitude_of_origin", "Latitude of false origin", 8821, UnitKind::Angular),
    (9817, "False easting", "False easting", 8806, UnitKind::Linear),
    (9817, "False northing", "False northing", 8807, UnitKind::Linear),
    (9817, "Latitude of natural origin", "Latitude of natural origin", 8801, UnitKind::Angular),
    (9817, "Longitude of natural origin", "Longitude of natural origin", 8802, UnitKind::Angular),
    (9817, "Scale factor at natural origin", "Scale factor at natural origin", 8805, UnitKind::Scale),
    (9818, "central_meridian", "Longitude of natural origin", 8802, UnitKind::Angular),
    (9818, "false_easting", "False easting", 8806, UnitKind::Linear),
    (9818, "false_northing", "False northing", 8807, UnitKind::Linear),
    (9818, "latitude_of_origin", "Latitude of natural origin", 8801, UnitKind::Angular),
    (9822, "false_easting", "Easting at false origin", 8826, UnitKind::Linear),
    (9822, "false_northing", "Northing at false origin", 8827, UnitKind::Linear),
    (9822, "latitude_of_center", "Latitude of false origin", 8821, UnitKind::Angular),
    (9822, "longitude_of_center", "Longitude of false origin", 8822, UnitKind::Angular),
    (9822, "standard_parallel_1", "Latitude of 1st standard parallel", 8823, UnitKind::Angular),
    (9822, "standard_parallel_2", "Latitude of 2nd standard parallel", 8824, UnitKind::Angular),
    (9824, "False easting", "False easting", 8806, UnitKind::Linear),
    (9824, "False northing", "False northing", 8807, UnitKind::Linear),
    (9824, "Initial longitude", "Initial longitude", 8830, UnitKind::Angular),
    (9824, "Latitude of natural origin", "Latitude of natural origin", 8801, UnitKind::Angular),
    (9824, "Scale factor at natural origin", "Scale factor at natural origin", 8805, UnitKind::Scale),
    (9824, "Zone width", "Zone width", 8831, UnitKind::Angular),
    (9826, "False easting", "False easting", 8806, UnitKind::Linear),
    (9826, "False northing", "False northing", 8807, UnitKind::Linear),
    (9826, "Latitude of natural origin", "Latitude of natural origin", 8801, UnitKind::Angular),
    (9826, "Longitude of natural origin", "Longitude of natural origin", 8802, UnitKind::Angular),
    (9826, "Scale factor at natural origin", "Scale factor at natural origin", 8805, UnitKind::Scale),
    (9828, "False easting", "False easting", 8806, UnitKind::Linear),
    (9828, "False northing", "False northing", 8807, UnitKind::Linear),
    (9828, "Latitude of natural origin", "Latitude of natural origin", 8801, UnitKind::Angular),
    (9828, "Longitude of natural origin", "Longitude of natural origin", 8802, UnitKind::Angular),
    (9830, "Easting at false origin", "Easting at false origin", 8826, UnitKind::Linear),
    (9830, "Latitude of standard parallel", "Latitude of standard parallel", 8832, UnitKind::Angular),
    (9830, "Longitude of origin", "Longitude of origin", 8833, UnitKind::Angular),
    (9830, "Northing at false origin", "Northing at false origin", 8827, UnitKind::Linear),
];

/// The WKT1 GDAL projection method name for an EPSG method code — the reverse
/// of `METHODS`' `wkt1_name -> epsg_code` direction, for `projjson_to_wkt`
/// (`wkt_projjson.rs`, `plans/projjson-to-wkt.org`). Exact within this
/// table's already-filtered common/unambiguous subset — no new crosswalk
/// data, just a scan of the existing static in the other direction. A method
/// code absent from `METHODS` (one no WKT1 source ever exercised) returns
/// `None`, same as the forward direction's own unresolved case.
pub(super) fn method_name_by_code(code: i64) -> Option<&'static str> {
    METHODS.iter().find(|(_, _, c, _)| *c == code).map(|(wkt1_name, ..)| *wkt1_name)
}

/// The WKT1 GDAL parameter name and unit kind for an `(EPSG method code,
/// EPSG parameter code)` pair — the reverse of `PARAMS`' direction, for
/// `projjson_to_wkt`. The unit kind rides along so the caller can validate a
/// PROJJSON parameter's own unit against what WKT1 expects (angular params
/// carry the base CRS's angular unit, linear params the projected CRS's own
/// linear unit, scale params are always dimensionless) without re-deriving it
/// from the JSON.
pub(super) fn param_by_code(method_code: i64, epsg_param_code: i64) -> Option<(&'static str, UnitKind)> {
    PARAMS
        .iter()
        .find(|(mc, _, _, pc, _)| *mc == method_code && *pc == epsg_param_code)
        .map(|(_, wkt1_name, _, _, kind)| (*wkt1_name, *kind))
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn every_method_round_trips_through_the_reverse_lookup() {
        for (wkt1_name, _, code, _) in METHODS {
            assert_eq!(method_name_by_code(*code), Some(*wkt1_name), "method code {code}");
        }
        assert_eq!(method_name_by_code(-1), None);
    }

    #[test]
    fn every_param_round_trips_through_the_reverse_lookup() {
        for (method_code, wkt1_name, _, epsg_code, kind) in PARAMS {
            assert_eq!(
                param_by_code(*method_code, *epsg_code),
                Some((*wkt1_name, *kind)),
                "method {method_code}, param {epsg_code}"
            );
        }
        assert_eq!(param_by_code(-1, -1), None);
    }
}
